[[keyboard.bindings]]
chars = "\f"
key = "R"
mode = "~Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ClearHistory"
key = "R"
mode = "~Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0001"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0005"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

# tmux tab navigation and management
[[keyboard.bindings]]
chars = "\u0001c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001&"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001p"
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001n"
key = "RBracket"
mods = "Command"

# tmux tab switching 1-9
[[keyboard.bindings]]
chars = "\u00011"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00012"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00013"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00014"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00015"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00016"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00017"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00018"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00019"
key = "Key9"
mods = "Command"

# Back key receives character
[[keyboard.bindings]]
action = "ReceiveChar"
key = "Back"

[terminal]

[general]
live_config_reload = true
import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/rose-pine.toml"
  # "~/.config/alacritty/rose-pine-moon.toml"
  # "~/.config/alacritty/rose-pine-dawn.toml"
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
]

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
shape = "Block"

[font]
size = 17.0

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.glyph_offset]
x = 0
y = 3

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 9

[scrolling]
history = 100000
multiplier = 4

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',│`|:"' ()[]{}<>'''

[window]
decorations = "transparent"

[window.dimensions]
columns = 106
lines = 25

[window.padding]
x = 20
y = 22

[terminal.shell]
program = "/bin/zsh"
args = ["--login", "-c", "tmux new-session -A -s main"]

[keyboard]
