# Lean Powerlevel10k preset tuned for the Rose Pine Alacritty + tmux workflow.

typeset -g POWERLEVEL9K_MODE='nerdfont-complete'
typeset -g POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true
typeset -g POWERLEVEL9K_INSTANT_PROMPT=off
typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=false

typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX=''
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=''
typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=' '
typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=' '
typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL=''

typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  dir
  vcs
  newline
  prompt_char
)

typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  status
  command_execution_time
  time
)

typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=''
typeset -g POWERLEVEL9K_DIR_BACKGROUND=''
typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=''
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=''
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=''
typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=''
typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=''
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=''
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=''
typeset -g POWERLEVEL9K_TIME_BACKGROUND=''
typeset -g POWERLEVEL9K_PROMPT_CHAR_BACKGROUND=''

typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND='#6e6a86'
typeset -g POWERLEVEL9K_DIR_FOREGROUND='#e0def4'
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='#e0def4'
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='#9ccfd8'
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND='#908caa'
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='#f6c177'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='#b4637a'
typeset -g POWERLEVEL9K_VCS_BRANCH_FOREGROUND='#908caa'
typeset -g POWERLEVEL9K_STATUS_OK=false
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND='#eb6f92'
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='#6e6a86'
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='#6e6a86'
typeset -g POWERLEVEL9K_TIME_FOREGROUND='#908caa'

typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=72
typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
typeset -g POWERLEVEL9K_SHORTEN_FOLDER_MARKER='(.git|.hg|.svn|package.json|Cargo.toml|go.mod|pyproject.toml|.mise.toml)'
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=5
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false
typeset -g POWERLEVEL9K_TIME_FORMAT='%H:%M'

typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND='#908caa'
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_CONTENT_EXPANSION='>'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND='#eb6f92'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_CONTENT_EXPANSION='>'
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_FOREGROUND='#9ccfd8'
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_CONTENT_EXPANSION='<'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_FOREGROUND='#eb6f92'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_CONTENT_EXPANSION='<'
